DELETE FROM com_app_user_ext;
DELETE FROM com_app_user_role_tree;
DELETE FROM com_app_user_tree;
DELETE FROM com_integral_note_info;
DELETE FROM com_invite_info;
DELETE FROM com_lbt_info;
DELETE FROM com_order_detail;
DELETE FROM com_order_main;
DELETE FROM com_product_category_detail;
DELETE FROM com_product_info;
DELETE FROM com_product_style_info;
DELETE FROM com_receive_address_info;
DELETE FROM com_shop_car_info;
DELETE FROM com_sparepart_deal_info;
DELETE FROM com_sparepart_info;
DELETE FROM com_style_category_tree;
DELETE FROM com_supplier_info;
UPDATE com_wx_account_info SET wxAccountStatus = '01' WHERE wxAccountCode = 'gemojp';
UPDATE com_wx_account_info SET wxAccountStatus = '00' WHERE wxAccountCode != 'gemojp';